services:
  # ДОМЕН 1: Пользователи и Самокаты
  identity_db:
    image: postgres:15
    environment:
      POSTGRES_DB: identity_fleet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - "5431:5432"

  # ДОМЕН 2: Шард 1 (Поездки и Логи)
  ops_shard_1:
    image: postgres:15
    environment:
      POSTGRES_DB: operations_sh1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - "5434:5432"

  # ДОМЕН 2: Шард 2 (Поездки и Логи)
  ops_shard_2:
    image: postgres:15
    environment:
      POSTGRES_DB: operations_sh2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - "5433:5432"

  # Экспортер для Identity
  postgres_exporter_id:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:p@ssw0rd@identity_db:5432/identity_fleet?sslmode=disable"
    ports:
      - "9187:9187"

  # Экспортер для Shard 1
  postgres_exporter_ops1:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:p@ssw0rd@ops_shard_1:5432/operations_sh1?sslmode=disable"
    ports:
      - "9188:9187"

  # Экспортер для Shard 2
  postgres_exporter_ops2:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:p@ssw0rd@ops_shard_2:5432/operations_sh2?sslmode=disable"
    ports:
      - "9189:9187"

  # МОНИТОРИНГ
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    restart: always   